runtime: nodejs
vm: true
api_version: 1

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.5

resources:
  cpu: .5
  memory_gb: 1.3
  disk_size_gb: 10